### ISSUE TITLE
Electricity verifyer: Implement withdraw ruleset

### ISSUE THREAD

**Issue by MartinSchmidt** [project-origin/verifier_electricity#128]
In the verifier, there must be a protobuf transaction for withdrawal, an implement the rules
```[tasklist]
### Tasks
- [ ] Define protobuf event for withdrawing a certificate
- [ ] Implement verifyer that verifies the event
- [ ] Verify that transaction is signed by area issuer key
- [ ] Ensure no other transactions can be executed afterwards
```
