### ISSUE TITLE
Electricity verifyer: Implement unclaim

### ISSUE THREAD

**Issue by tnickelsen** [project-origin/verifier_electricity#136]
### Description

We must implement unclaim event so claims where the other certificate has been withdrawn can be unclaimed

```[tasklist]
### Tasks
- [ ] Implement protobuf spec
- [ ] Implement verifyer that verifyes that the other certificate is withdrawn
- [ ] Must be signed by the owner of the slice
- [ ] Implement event in model
```
